# Generated by Django 5.2.3 on 2025-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajemision',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('en_progreso', 'En progreso'), ('fallida', 'Fallida')], default='pendiente', max_length=20),
        ),
    ]
